# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles /app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named video_sdk_core

# Build rule for target.
video_sdk_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 video_sdk_core
.PHONY : video_sdk_core

# fast build rule for target.
video_sdk_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/build
.PHONY : video_sdk_core/fast

#=============================================================================
# Target rules for targets named test_filter_graph

# Build rule for target.
test_filter_graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_filter_graph
.PHONY : test_filter_graph

# fast build rule for target.
test_filter_graph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_filter_graph.dir/build.make CMakeFiles/test_filter_graph.dir/build
.PHONY : test_filter_graph/fast

#=============================================================================
# Target rules for targets named test_render_angle

# Build rule for target.
test_render_angle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_render_angle
.PHONY : test_render_angle

# fast build rule for target.
test_render_angle/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_render_angle.dir/build.make CMakeFiles/test_render_angle.dir/build
.PHONY : test_render_angle/fast

core/src/Filter.o: core/src/Filter.cpp.o
.PHONY : core/src/Filter.o

# target to build an object file
core/src/Filter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/Filter.cpp.o
.PHONY : core/src/Filter.cpp.o

core/src/Filter.i: core/src/Filter.cpp.i
.PHONY : core/src/Filter.i

# target to preprocess a source file
core/src/Filter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/Filter.cpp.i
.PHONY : core/src/Filter.cpp.i

core/src/Filter.s: core/src/Filter.cpp.s
.PHONY : core/src/Filter.s

# target to generate assembly for a file
core/src/Filter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/Filter.cpp.s
.PHONY : core/src/Filter.cpp.s

core/src/FilterEngine.o: core/src/FilterEngine.cpp.o
.PHONY : core/src/FilterEngine.o

# target to build an object file
core/src/FilterEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/FilterEngine.cpp.o
.PHONY : core/src/FilterEngine.cpp.o

core/src/FilterEngine.i: core/src/FilterEngine.cpp.i
.PHONY : core/src/FilterEngine.i

# target to preprocess a source file
core/src/FilterEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/FilterEngine.cpp.i
.PHONY : core/src/FilterEngine.cpp.i

core/src/FilterEngine.s: core/src/FilterEngine.cpp.s
.PHONY : core/src/FilterEngine.s

# target to generate assembly for a file
core/src/FilterEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/FilterEngine.cpp.s
.PHONY : core/src/FilterEngine.cpp.s

core/src/Filters.o: core/src/Filters.cpp.o
.PHONY : core/src/Filters.o

# target to build an object file
core/src/Filters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/Filters.cpp.o
.PHONY : core/src/Filters.cpp.o

core/src/Filters.i: core/src/Filters.cpp.i
.PHONY : core/src/Filters.i

# target to preprocess a source file
core/src/Filters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/Filters.cpp.i
.PHONY : core/src/Filters.cpp.i

core/src/Filters.s: core/src/Filters.cpp.s
.PHONY : core/src/Filters.s

# target to generate assembly for a file
core/src/Filters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/Filters.cpp.s
.PHONY : core/src/Filters.cpp.s

core/src/FrameBuffer.o: core/src/FrameBuffer.cpp.o
.PHONY : core/src/FrameBuffer.o

# target to build an object file
core/src/FrameBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/FrameBuffer.cpp.o
.PHONY : core/src/FrameBuffer.cpp.o

core/src/FrameBuffer.i: core/src/FrameBuffer.cpp.i
.PHONY : core/src/FrameBuffer.i

# target to preprocess a source file
core/src/FrameBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/FrameBuffer.cpp.i
.PHONY : core/src/FrameBuffer.cpp.i

core/src/FrameBuffer.s: core/src/FrameBuffer.cpp.s
.PHONY : core/src/FrameBuffer.s

# target to generate assembly for a file
core/src/FrameBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/FrameBuffer.cpp.s
.PHONY : core/src/FrameBuffer.cpp.s

core/src/FrameBufferPool.o: core/src/FrameBufferPool.cpp.o
.PHONY : core/src/FrameBufferPool.o

# target to build an object file
core/src/FrameBufferPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/FrameBufferPool.cpp.o
.PHONY : core/src/FrameBufferPool.cpp.o

core/src/FrameBufferPool.i: core/src/FrameBufferPool.cpp.i
.PHONY : core/src/FrameBufferPool.i

# target to preprocess a source file
core/src/FrameBufferPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/FrameBufferPool.cpp.i
.PHONY : core/src/FrameBufferPool.cpp.i

core/src/FrameBufferPool.s: core/src/FrameBufferPool.cpp.s
.PHONY : core/src/FrameBufferPool.s

# target to generate assembly for a file
core/src/FrameBufferPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/video_sdk_core.dir/build.make CMakeFiles/video_sdk_core.dir/core/src/FrameBufferPool.cpp.s
.PHONY : core/src/FrameBufferPool.cpp.s

tests/test_filter_graph.o: tests/test_filter_graph.cpp.o
.PHONY : tests/test_filter_graph.o

# target to build an object file
tests/test_filter_graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_filter_graph.dir/build.make CMakeFiles/test_filter_graph.dir/tests/test_filter_graph.cpp.o
.PHONY : tests/test_filter_graph.cpp.o

tests/test_filter_graph.i: tests/test_filter_graph.cpp.i
.PHONY : tests/test_filter_graph.i

# target to preprocess a source file
tests/test_filter_graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_filter_graph.dir/build.make CMakeFiles/test_filter_graph.dir/tests/test_filter_graph.cpp.i
.PHONY : tests/test_filter_graph.cpp.i

tests/test_filter_graph.s: tests/test_filter_graph.cpp.s
.PHONY : tests/test_filter_graph.s

# target to generate assembly for a file
tests/test_filter_graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_filter_graph.dir/build.make CMakeFiles/test_filter_graph.dir/tests/test_filter_graph.cpp.s
.PHONY : tests/test_filter_graph.cpp.s

tests/test_render_angle.o: tests/test_render_angle.cpp.o
.PHONY : tests/test_render_angle.o

# target to build an object file
tests/test_render_angle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_render_angle.dir/build.make CMakeFiles/test_render_angle.dir/tests/test_render_angle.cpp.o
.PHONY : tests/test_render_angle.cpp.o

tests/test_render_angle.i: tests/test_render_angle.cpp.i
.PHONY : tests/test_render_angle.i

# target to preprocess a source file
tests/test_render_angle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_render_angle.dir/build.make CMakeFiles/test_render_angle.dir/tests/test_render_angle.cpp.i
.PHONY : tests/test_render_angle.cpp.i

tests/test_render_angle.s: tests/test_render_angle.cpp.s
.PHONY : tests/test_render_angle.s

# target to generate assembly for a file
tests/test_render_angle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_render_angle.dir/build.make CMakeFiles/test_render_angle.dir/tests/test_render_angle.cpp.s
.PHONY : tests/test_render_angle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_filter_graph"
	@echo "... test_render_angle"
	@echo "... video_sdk_core"
	@echo "... core/src/Filter.o"
	@echo "... core/src/Filter.i"
	@echo "... core/src/Filter.s"
	@echo "... core/src/FilterEngine.o"
	@echo "... core/src/FilterEngine.i"
	@echo "... core/src/FilterEngine.s"
	@echo "... core/src/Filters.o"
	@echo "... core/src/Filters.i"
	@echo "... core/src/Filters.s"
	@echo "... core/src/FrameBuffer.o"
	@echo "... core/src/FrameBuffer.i"
	@echo "... core/src/FrameBuffer.s"
	@echo "... core/src/FrameBufferPool.o"
	@echo "... core/src/FrameBufferPool.i"
	@echo "... core/src/FrameBufferPool.s"
	@echo "... tests/test_filter_graph.o"
	@echo "... tests/test_filter_graph.i"
	@echo "... tests/test_filter_graph.s"
	@echo "... tests/test_render_angle.o"
	@echo "... tests/test_render_angle.i"
	@echo "... tests/test_render_angle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
