#pragma once
#include <string>
#include <unordered_map>

namespace sdk {
namespace video {

struct GeneratedShaders {
    static const std::unordered_map<std::string, std::string>& get() {
        static const std::unordered_map<std::string, std::string> shaders = {
            {"oes.vert",
            "#version 300 es\n"
            "layout(location = 0) in vec4 position;\n"
            "layout(location = 1) in vec4 inputTextureCoordinate;\n"
            "uniform mat4 textureMatrix;\n"
            "uniform bool flipHorizontal;\n"
            "uniform bool flipVertical;\n"
            "out vec2 textureCoordinate;\n"
            "void main() {\n"
            "    gl_Position = position;\n"
            "    vec2 flippedCoord = inputTextureCoordinate.xy;\n"
            "    if (flipHorizontal) {\n"
            "        flippedCoord.x = 1.0 - flippedCoord.x;\n"
            "    }\n"
            "    if (flipVertical) {\n"
            "        flippedCoord.y = 1.0 - flippedCoord.y;\n"
            "    }\n"
            "    textureCoordinate = (textureMatrix * vec4(flippedCoord, 0.0, 1.0)).xy;\n"
            "}\n"
            ""},
            {"gaussian_blur.frag",
            "#version 300 es\n"
            "precision mediump float;\n"
            "\n"
            "uniform sampler2D inputImageTexture;\n"
            "in vec2 blurCoordinates[5];\n"
            "\n"
            "out vec4 fragColor;\n"
            "\n"
            "void main() {\n"
            "    vec4 sum = vec4(0.0);\n"
            "    sum += texture(inputImageTexture, blurCoordinates[0]) * 0.204164;\n"
            "    sum += texture(inputImageTexture, blurCoordinates[1]) * 0.304005;\n"
            "    sum += texture(inputImageTexture, blurCoordinates[2]) * 0.304005;\n"
            "    sum += texture(inputImageTexture, blurCoordinates[3]) * 0.093913;\n"
            "    sum += texture(inputImageTexture, blurCoordinates[4]) * 0.093913;\n"
            "    fragColor = sum;\n"
            "}\n"
            ""},
            {"compositor_wipe.frag",
            "#version 300 es\n"
            "precision highp float;\n"
            "in vec2 v_texCoord;\n"
            "uniform sampler2D texBackground;\n"
            "uniform sampler2D texForeground;\n"
            "uniform float progress; // 0.0 to 1.0\n"
            "out vec4 fragColor;\n"
            "\n"
            "void main() {\n"
            "    vec4 bg = texture(texBackground, v_texCoord);\n"
            "    vec4 fg = texture(texForeground, v_texCoord);\n"
            "    \n"
            "    // Wipe from left to right\n"
            "    if (v_texCoord.x < progress) {\n"
            "        fragColor = fg;\n"
            "    } else {\n"
            "        fragColor = bg;\n"
            "    }\n"
            "}\n"
            ""},
            {"compositor_wipe.vert",
            "#version 300 es\n"
            "layout(location = 0) in vec4 position;\n"
            "layout(location = 1) in vec2 texCoord;\n"
            "out vec2 v_texCoord;\n"
            "void main() {\n"
            "    gl_Position = position;\n"
            "    v_texCoord = texCoord;\n"
            "}\n"
            ""},
            {"lookup.frag",
            "#version 300 es\n"
            "precision mediump float;\n"
            "in vec2 textureCoordinate;\n"
            "out vec4 fragColor;\n"
            "\n"
            "uniform sampler2D inputImageTexture;\n"
            "uniform sampler2D lookupTexture;\n"
            "uniform float intensity;\n"
            "\n"
            "void main() {\n"
            "    vec4 textureColor = texture(inputImageTexture, textureCoordinate);\n"
            "\n"
            "    float blueColor = textureColor.b * 63.0;\n"
            "\n"
            "    vec2 quad1;\n"
            "    quad1.y = floor(floor(blueColor) / 8.0);\n"
            "    quad1.x = floor(blueColor) - (quad1.y * 8.0);\n"
            "\n"
            "    vec2 quad2;\n"
            "    quad2.y = floor(ceil(blueColor) / 8.0);\n"
            "    quad2.x = ceil(blueColor) - (quad2.y * 8.0);\n"
            "\n"
            "    vec2 texPos1;\n"
            "    texPos1.x = (quad1.x * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * textureColor.r);\n"
            "    texPos1.y = (quad1.y * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * textureColor.g);\n"
            "\n"
            "    vec2 texPos2;\n"
            "    texPos2.x = (quad2.x * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * textureColor.r);\n"
            "    texPos2.y = (quad2.y * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * textureColor.g);\n"
            "\n"
            "    vec4 newColor1 = texture(lookupTexture, texPos1);\n"
            "    vec4 newColor2 = texture(lookupTexture, texPos2);\n"
            "\n"
            "    vec4 newColor = mix(newColor1, newColor2, fract(blueColor));\n"
            "    fragColor = mix(textureColor, vec4(newColor.rgb, textureColor.w), intensity);\n"
            "}\n"
            ""},
            {"compositor_blend.frag",
            "#version 300 es\n"
            "precision highp float;\n"
            "in vec2 v_texCoord;\n"
            "uniform sampler2D texBackground;\n"
            "uniform sampler2D texForeground;\n"
            "uniform float opacity;\n"
            "out vec4 fragColor;\n"
            "\n"
            "void main() {\n"
            "    vec4 bg = texture(texBackground, v_texCoord);\n"
            "    vec4 fg = texture(texForeground, v_texCoord);\n"
            "    \n"
            "    // Normal alpha blending\n"
            "    vec3 color = mix(bg.rgb, fg.rgb, fg.a * opacity);\n"
            "    float alpha = bg.a + fg.a * opacity * (1.0 - bg.a);\n"
            "    \n"
            "    fragColor = vec4(color, alpha);\n"
            "}\n"
            ""},
            {"cinematic_lookup.frag",
            "#version 300 es\n"
            "precision highp float;\n"
            "in vec2 textureCoordinate;\n"
            "uniform sampler2D inputImageTexture;\n"
            "uniform sampler2D lookupTexture;\n"
            "uniform float intensity;\n"
            "\n"
            "out vec4 fragColor;\n"
            "\n"
            "void main() {\n"
            "    vec4 textureColor = texture(inputImageTexture, textureCoordinate);\n"
            "\n"
            "    // 计算 3D LUT (Look-Up Table) 的坐标映射\n"
            "    float blueColor = textureColor.b * 63.0;\n"
            "\n"
            "    vec2 quad1;\n"
            "    quad1.y = floor(floor(blueColor) / 8.0);\n"
            "    quad1.x = floor(blueColor) - (quad1.y * 8.0);\n"
            "\n"
            "    vec2 quad2;\n"
            "    quad2.y = floor(ceil(blueColor) / 8.0);\n"
            "    quad2.x = ceil(blueColor) - (quad2.y * 8.0);\n"
            "\n"
            "    vec2 texPos1;\n"
            "    texPos1.x = (quad1.x * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * textureColor.r);\n"
            "    texPos1.y = (quad1.y * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * textureColor.g);\n"
            "\n"
            "    vec2 texPos2;\n"
            "    texPos2.x = (quad2.x * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * textureColor.r);\n"
            "    texPos2.y = (quad2.y * 0.125) + 0.5/512.0 + ((0.125 - 1.0/512.0) * textureColor.g);\n"
            "\n"
            "    vec4 newColor1 = texture(lookupTexture, texPos1);\n"
            "    vec4 newColor2 = texture(lookupTexture, texPos2);\n"
            "\n"
            "    vec4 newColor = mix(newColor1, newColor2, fract(blueColor));\n"
            "\n"
            "    // 增加一定的胶片颗粒噪点感 (Film Grain) 或者 Vignette (暗角)，作为\"电影感\"的体现\n"
            "    float dist = distance(textureCoordinate, vec2(0.5, 0.5));\n"
            "    newColor.rgb *= smoothstep(0.8, 0.3, dist); // Vignette\n"
            "\n"
            "    fragColor = mix(textureColor, vec4(newColor.rgb, textureColor.w), intensity);\n"
            "}\n"
            ""},
            {"compositor_blend.vert",
            "#version 300 es\n"
            "layout(location = 0) in vec4 position;\n"
            "layout(location = 1) in vec2 texCoord;\n"
            "out vec2 v_texCoord;\n"
            "void main() {\n"
            "    gl_Position = position;\n"
            "    v_texCoord = texCoord;\n"
            "}\n"
            ""},
            {"bilateral.frag",
            "#version 300 es\n"
            "precision mediump float;\n"
            "\n"
            "in vec2 textureCoordinate;\n"
            "out vec4 fragColor;\n"
            "\n"
            "uniform sampler2D inputImageTexture;\n"
            "\n"
            "uniform float texelWidthOffset;\n"
            "uniform float texelHeightOffset;\n"
            "uniform float distanceNormalizationFactor; // Control smoothing strength\n"
            "\n"
            "void main() {\n"
            "    vec4 centralColor = texture(inputImageTexture, textureCoordinate);\n"
            "\n"
            "    // Quick escape for low smoothing (acts as passthrough or just performance saver)\n"
            "    if (distanceNormalizationFactor < 0.1) {\n"
            "        fragColor = centralColor;\n"
            "        return;\n"
            "    }\n"
            "\n"
            "    float gaussianWeightTotal = 0.15;\n"
            "    vec4 sum = centralColor * 0.15;\n"
            "\n"
            "    vec2 singleStepOffset = vec2(texelWidthOffset, texelHeightOffset);\n"
            "\n"
            "    float distance_diff;\n"
            "    vec4 sampleColor;\n"
            "    float weight;\n"
            "\n"
            "    // A simplified 3x3 bilateral filter kernel for real-time mobile performance\n"
            "    // It compares the central pixel color with neighbors. Neighbors with similar colors\n"
            "    // get higher weights (smoothing continuous areas like skin), while sharp edges\n"
            "    // are preserved because of high color difference lowering the weight.\n"
            "\n"
            "    // (-1, -1)\n"
            "    sampleColor = texture(inputImageTexture, textureCoordinate - singleStepOffset);\n"
            "    distance_diff = distance(centralColor.rgb, sampleColor.rgb);\n"
            "    weight = 0.05 * exp(-distance_diff * distance_diff * distanceNormalizationFactor);\n"
            "    sum += sampleColor * weight;\n"
            "    gaussianWeightTotal += weight;\n"
            "\n"
            "    // (0, -1)\n"
            "    sampleColor = texture(inputImageTexture, textureCoordinate - vec2(0.0, singleStepOffset.y));\n"
            "    distance_diff = distance(centralColor.rgb, sampleColor.rgb);\n"
            "    weight = 0.10 * exp(-distance_diff * distance_diff * distanceNormalizationFactor);\n"
            "    sum += sampleColor * weight;\n"
            "    gaussianWeightTotal += weight;\n"
            "\n"
            "    // (1, -1)\n"
            "    sampleColor = texture(inputImageTexture, textureCoordinate + vec2(singleStepOffset.x, -singleStepOffset.y));\n"
            "    distance_diff = distance(centralColor.rgb, sampleColor.rgb);\n"
            "    weight = 0.05 * exp(-distance_diff * distance_diff * distanceNormalizationFactor);\n"
            "    sum += sampleColor * weight;\n"
            "    gaussianWeightTotal += weight;\n"
            "\n"
            "    // (-1, 0)\n"
            "    sampleColor = texture(inputImageTexture, textureCoordinate - vec2(singleStepOffset.x, 0.0));\n"
            "    distance_diff = distance(centralColor.rgb, sampleColor.rgb);\n"
            "    weight = 0.10 * exp(-distance_diff * distance_diff * distanceNormalizationFactor);\n"
            "    sum += sampleColor * weight;\n"
            "    gaussianWeightTotal += weight;\n"
            "\n"
            "    // (1, 0)\n"
            "    sampleColor = texture(inputImageTexture, textureCoordinate + vec2(singleStepOffset.x, 0.0));\n"
            "    distance_diff = distance(centralColor.rgb, sampleColor.rgb);\n"
            "    weight = 0.10 * exp(-distance_diff * distance_diff * distanceNormalizationFactor);\n"
            "    sum += sampleColor * weight;\n"
            "    gaussianWeightTotal += weight;\n"
            "\n"
            "    // (-1, 1)\n"
            "    sampleColor = texture(inputImageTexture, textureCoordinate + vec2(-singleStepOffset.x, singleStepOffset.y));\n"
            "    distance_diff = distance(centralColor.rgb, sampleColor.rgb);\n"
            "    weight = 0.05 * exp(-distance_diff * distance_diff * distanceNormalizationFactor);\n"
            "    sum += sampleColor * weight;\n"
            "    gaussianWeightTotal += weight;\n"
            "\n"
            "    // (0, 1)\n"
            "    sampleColor = texture(inputImageTexture, textureCoordinate + vec2(0.0, singleStepOffset.y));\n"
            "    distance_diff = distance(centralColor.rgb, sampleColor.rgb);\n"
            "    weight = 0.10 * exp(-distance_diff * distance_diff * distanceNormalizationFactor);\n"
            "    sum += sampleColor * weight;\n"
            "    gaussianWeightTotal += weight;\n"
            "\n"
            "    // (1, 1)\n"
            "    sampleColor = texture(inputImageTexture, textureCoordinate + singleStepOffset);\n"
            "    distance_diff = distance(centralColor.rgb, sampleColor.rgb);\n"
            "    weight = 0.05 * exp(-distance_diff * distance_diff * distanceNormalizationFactor);\n"
            "    sum += sampleColor * weight;\n"
            "    gaussianWeightTotal += weight;\n"
            "\n"
            "    fragColor = vec4(sum.rgb / gaussianWeightTotal, centralColor.a);\n"
            "}"},
            {"oes.frag",
            "#version 300 es\n"
            "#extension GL_OES_EGL_image_external_essl3 : require\n"
            "precision mediump float;\n"
            "in vec2 textureCoordinate;\n"
            "out vec4 fragColor;\n"
            "uniform samplerExternalOES inputImageTexture;\n"
            "\n"
            "void main() {\n"
            "    fragColor = texture(inputImageTexture, textureCoordinate);\n"
            "}\n"
            ""},
            {"compositor_copy.vert",
            "#version 300 es\n"
            "layout(location = 0) in vec4 position;\n"
            "layout(location = 1) in vec2 texCoord;\n"
            "out vec2 v_texCoord;\n"
            "void main() {\n"
            "    gl_Position = position;\n"
            "    v_texCoord = texCoord;\n"
            "}\n"
            ""},
            {"brightness.frag",
            "#version 300 es\n"
            "precision mediump float;\n"
            "in vec2 textureCoordinate;\n"
            "out vec4 fragColor;\n"
            "uniform sampler2D inputImageTexture;\n"
            "uniform float brightness;\n"
            "\n"
            "void main() {\n"
            "    vec4 textureColor = texture(inputImageTexture, textureCoordinate);\n"
            "    fragColor = vec4((textureColor.rgb + vec3(brightness)), textureColor.w);\n"
            "}\n"
            ""},
            {"compositor_copy.frag",
            "#version 300 es\n"
            "precision highp float;\n"
            "in vec2 v_texCoord;\n"
            "uniform sampler2D texForeground;\n"
            "uniform float opacity;\n"
            "out vec4 fragColor;\n"
            "void main() {\n"
            "    vec4 fg = texture(texForeground, v_texCoord);\n"
            "    fragColor = vec4(fg.rgb, fg.a * opacity);\n"
            "}\n"
            ""},
        };
        return shaders;
    }
};

} // namespace video
} // namespace sdk
